from _typeshed import Incomplete

def create_network_dict(app, flag_graphics: str = "GPS"): ...
def get_lvp_params(app): ...
def get_global_parameters(app): ...
def gather_graphic_objects(app, dict_net, dia_name) -> None: ...
def apply_unit_settings(app, elm_units, exponent) -> None: ...
def run_load_flow(
    app,
    scale_feeder_loads: bool = False,
    load_scaling: Incomplete | None = None,
    gen_scaling: Incomplete | None = None,
    motor_scaling: Incomplete | None = None,
): ...
def setup_unit_exponents(prj, elm_class, unit, exponent) -> None: ...
def setup_project_power_exponent(prj, exponent) -> None: ...
