import logging
from abc import ABC, abstractmethod
from collections import defaultdict
from typing import Any, Literal, SupportsIndex, overload

import pandas as pd

from pandapower.auxiliary import ADict, pandapowerNet

def add_log_level(levelno: int, levelname: str) -> None: ...

class DiagnosticFunction[N: ADict[Any], T](ABC):
    def __init__(self) -> None: ...
    @abstractmethod
    def diagnostic(self, net: N, **kwargs) -> T | None: ...
    @abstractmethod
    def report(self, error: Exception | None, results: T | None) -> None: ...

class NotCompactFilter(logging.Filter): ...
class NotDetailedFilter(logging.Filter): ...

class LogCount(logging.Filter):
    count: defaultdict[int, int]
    def __init__(self) -> None: ...
    def cd_in_count(self) -> bool: ...
    def reset(self) -> None: ...

def check_boolean[T: SupportsIndex](element: pd.Series[Any], element_index: T, column: str) -> T | None: ...
def check_greater_equal_zero[T: SupportsIndex](element: pd.Series[Any], element_index: T, column: str) -> T | None: ...
def check_greater_zero[T: SupportsIndex](element: pd.Series[Any], element_index: T, column: str) -> T | None: ...
def check_greater_zero_less_equal_one(element: pd.Series[Any], element_index: int, column: str) -> int | None: ...
def check_less_15[T: SupportsIndex](element: pd.Series[Any], element_index: T, column: str) -> T | None: ...
def check_less_20[T: SupportsIndex](element: pd.Series[Any], element_index: T, column: str) -> T | None: ...
def check_less_equal_zero[T: SupportsIndex](element: pd.Series[Any], element_index: T, column: str) -> T | None: ...
def check_less_zero[T: SupportsIndex](element: pd.Series[Any], element_index: T, column: str) -> T | None: ...
def check_number[T: SupportsIndex](element: pd.Series[Any], element_index: T, column: str) -> T | None: ...
def check_pos_int[T: SupportsIndex](element: pd.Series[Any], element_index: T, column: str) -> T | None: ...
def check_switch_type(element: pd.Series[Any], element_index: int, column: str) -> int | None: ...
@overload
def diagnostic(
    net: pandapowerNet,
    report_style: Literal["detailed", "compact"] | None = "detailed",
    warnings_only: bool = False,
    return_result_dict: Literal[True] = True,
    overload_scaling_factor: float = 0.001,
    lines_min_length_km: float = 0.0,
    lines_min_z_ohm: float = 0.0,
    nom_voltage_tolerance: float = 0.3,
    **kwargs,
) -> dict[str, Any]: ...
@overload
def diagnostic(
    net: pandapowerNet,
    *,
    report_style: Literal["detailed", "compact"] | None = "detailed",
    warnings_only: bool = False,
    return_result_dict: Literal[False],
    overload_scaling_factor: float = 0.001,
    lines_min_length_km: float = 0.0,
    lines_min_z_ohm: float = 0.0,
    nom_voltage_tolerance: float = 0.3,
    **kwargs,
) -> None: ...
