from typing import Any

from pandapower.auxiliary import pandapowerNet
from pandapower.diagnostic.diagnostic_helpers import DiagnosticFunction

expected_exceptions: tuple[type[Exception], ...]
default_argument_values: dict[str, float]

class InvalidValues(DiagnosticFunction[pandapowerNet, dict[str, Any]]):
    def diagnostic(self, net: pandapowerNet, **kwargs) -> dict[str, Any] | None: ...
    def report(self, error: Exception | None, results: dict[str, Any] | None) -> None: ...

class NoExtGrid(DiagnosticFunction[pandapowerNet, bool]):
    def diagnostic(self, net: pandapowerNet, **kwargs) -> bool | None: ...
    def report(self, error: Exception | None, results: bool | None) -> None: ...

class MultipleVoltageControllingElementsPerBus(DiagnosticFunction[pandapowerNet, dict[str, list[Any]]]):
    def diagnostic(self, net: pandapowerNet, **kwargs) -> dict[str, list[Any]] | None: ...
    def report(self, error: Exception | None, results: dict[str, list[Any]] | None) -> None: ...

class Overload(DiagnosticFunction[pandapowerNet, dict[str, bool]]):
    def diagnostic(self, net: pandapowerNet, **kwargs) -> dict[str, bool] | None: ...
    def report(self, error: Exception | None, results: dict[str, bool] | None) -> None: ...

class WrongLineCapacitance(DiagnosticFunction[pandapowerNet, bool]):
    def diagnostic(self, net: pandapowerNet, **kwargs) -> bool | None: ...
    def report(self, error: Exception | None, results: bool | None) -> None: ...

class SubNetProblemTest(DiagnosticFunction[pandapowerNet, dict[str, bool]]):
    def diagnostic(self, net: pandapowerNet, **kwargs) -> dict[str, bool] | None: ...
    def report(self, error: Exception | None, results: dict[str, bool] | None) -> None: ...

class OptimisticPowerflow(DiagnosticFunction[pandapowerNet, dict[str, bool]]):
    def diagnostic(self, net: pandapowerNet, **kwargs) -> dict[str, bool] | None: ...
    def report(self, error: Exception | None, results: dict[str, bool] | None) -> None: ...

class SlackGenPlacement(DiagnosticFunction[pandapowerNet, dict[str, float]]):
    def diagnostic(self, net: pandapowerNet, **kwargs) -> dict[str, float] | None: ...
    def report(self, error: Exception | None, results: dict[str, float] | None) -> None: ...

class TestContinuousBusIndices(DiagnosticFunction[pandapowerNet, bool]):
    def diagnostic(self, net: pandapowerNet, **kwargs) -> bool | None: ...
    def report(self, error: Exception | None, results: bool | None) -> None: ...

class WrongSwitchConfiguration(DiagnosticFunction[pandapowerNet, bool]):
    def diagnostic(self, net: pandapowerNet, **kwargs) -> bool | None: ...
    def report(self, error: Exception | None, results: bool | None) -> None: ...

class MissingBusIndices(DiagnosticFunction[pandapowerNet, dict[str, list[tuple[int, str, int]]]]):
    def diagnostic(self, net: pandapowerNet, **kwargs) -> dict[str, list[tuple[int, str, int]]] | None: ...
    def report(self, error: Exception | None, results: dict[str, list[tuple[int, str, int]]] | None) -> None: ...

class DifferentVoltageLevelsConnected(DiagnosticFunction[pandapowerNet, dict[str, list[int]]]):
    def diagnostic(self, net: pandapowerNet, **kwargs) -> dict[str, list[int]] | None: ...
    def report(self, error: Exception | None, results: dict[str, list[int]] | None) -> None: ...

class ImplausibleImpedanceValues(DiagnosticFunction[pandapowerNet, list[dict[str, list[int]]]]):
    def diagnostic(self, net: pandapowerNet, **kwargs) -> list[dict[str, list[int]]] | None: ...
    def report(self, error: Exception | None, results: list[dict[str, list[int]]] | None) -> None: ...

class NominalVoltagesMismatch(DiagnosticFunction[pandapowerNet, dict[str, dict[str, list[int]]]]):
    def diagnostic(self, net: pandapowerNet, **kwargs) -> dict[str, dict[str, list[int]]] | None: ...
    def report(self, error: Exception | None, results: dict[str, dict[str, list[int]]] | None) -> None: ...

class DisconnectedElements(DiagnosticFunction[pandapowerNet, list[dict[str, list[int]]]]):
    def diagnostic(self, net: pandapowerNet, **kwargs) -> list[dict[str, list[int]]] | None: ...
    def report(self, error: Exception | None, results: list[dict[str, list[int]]] | None) -> None: ...

class WrongReferenceSystem(DiagnosticFunction[pandapowerNet, dict[str, list[int]]]):
    def diagnostic(self, net: pandapowerNet, **kwargs) -> dict[str, list[int]] | None: ...
    def report(self, error: Exception | None, results: dict[str, list[int]] | None) -> None: ...

class NumbaComparison(DiagnosticFunction[pandapowerNet, dict[str, dict[str, float]]]):
    def diagnostic(self, net: pandapowerNet, **kwargs) -> dict[str, dict[str, float]] | None: ...
    def report(self, error: Exception | None, results: dict[str, dict[str, float]] | None) -> None: ...

class DeviationFromStdType(DiagnosticFunction[pandapowerNet, dict[str, dict[str, dict[int, dict[str, Any]]]]]):
    def diagnostic(self, net: pandapowerNet, **kwargs) -> dict[str, dict[str, dict[int, dict[str, Any]]]] | None: ...
    def report(self, error: Exception | None, results: dict[str, dict[str, dict[int, dict[str, Any]]]] | None) -> None: ...

class ParallelSwitches(DiagnosticFunction[pandapowerNet, list[list[int]]]):
    def diagnostic(self, net: pandapowerNet, **kwargs) -> list[list[int]] | None: ...
    def report(self, error: Exception | None, results: list[list[int]] | None) -> None: ...

default_diagnostic_functions: list[tuple[str, DiagnosticFunction[pandapowerNet, Any], list[str] | None]]
