from collections.abc import Collection
from typing import Literal, TypeVar, overload
from typing_extensions import TypeAlias

from shapely.geometry.base import BaseGeometry
from shapely.geometry.point import Point

__all__ = ["affine_transform", "rotate", "scale", "skew", "translate"]

_GeoT = TypeVar("_GeoT", bound=BaseGeometry)
_Origin: TypeAlias = Literal["center", "centroid"] | Point | tuple[float, float] | tuple[float, float, float]

def affine_transform(geom: _GeoT, matrix: Collection[float]) -> _GeoT: ...
@overload
def interpret_origin(geom: BaseGeometry, origin: _Origin, ndim: Literal[2]) -> tuple[float, float]: ...
@overload
def interpret_origin(geom: BaseGeometry, origin: _Origin, ndim: Literal[3]) -> tuple[float, float, float]: ...
def rotate(geom: _GeoT, angle: float, origin: _Origin = "center", use_radians: bool = False) -> _GeoT: ...
def scale(geom: _GeoT, xfact: float = 1.0, yfact: float = 1.0, zfact: float = 1.0, origin: _Origin = "center") -> _GeoT: ...
def skew(geom: _GeoT, xs: float = 0.0, ys: float = 0.0, origin: _Origin = "center", use_radians: bool = False) -> _GeoT: ...
def translate(geom: _GeoT, xoff: float = 0.0, yoff: float = 0.0, zoff: float = 0.0) -> _GeoT: ...
