from shapely._typing import ArrayLike

__all__ = ["line_interpolate_point", "line_locate_point", "line_merge", "shared_paths", "shortest_line"]

def line_interpolate_point(line, distance: ArrayLike[float], normalized: bool = False, **kwargs): ...
def line_locate_point(line, other, normalized: bool = False, **kwargs): ...
def line_merge(line, directed: bool = False, **kwargs): ...
def shared_paths(a, b, **kwargs): ...
def shortest_line(a, b, **kwargs): ...
