from _typeshed import SupportsRead, SupportsWrite
from typing import Literal, overload

from shapely.geometry.base import BaseGeometry

def loads(data: str | bytes, hex: bool = False) -> BaseGeometry: ...
def load(fp: SupportsRead[str] | SupportsRead[bytes], hex: bool = False): ...
@overload
def dumps(ob: BaseGeometry, hex: Literal[False] = False, srid: int | None = None, **kw) -> bytes: ...
@overload
def dumps(ob: BaseGeometry, hex: Literal[True], srid: int | None = None, **kw) -> str: ...
@overload
def dump(ob: BaseGeometry, fp: SupportsWrite[bytes], hex: Literal[False] = False, *, srid: int | None = None, **kw) -> None: ...
@overload
def dump(ob: BaseGeometry, fp: SupportsWrite[str], hex: Literal[True], *, srid: int | None = None, **kw) -> None: ...
