from _typeshed import Incomplete

from psqlextra.backend.migrations.operations.partition import PostgresPartitionOperation

class PostgresAddRangePartition(PostgresPartitionOperation):
    from_values: Incomplete
    to_values: Incomplete
    def __init__(self, model_name: str, name: str, from_values, to_values) -> None: ...
    def state_forwards(self, app_label, state) -> None: ...
    def database_forwards(self, app_label, schema_editor, from_state, to_state) -> None: ...
    def database_backwards(self, app_label, schema_editor, from_state, to_state) -> None: ...
    def deconstruct(self): ...
    def describe(self) -> str: ...
