from psqlextra.backend.migrations.operations.partition import PostgresPartitionOperation

class PostgresDeletePartition(PostgresPartitionOperation):
    def state_forwards(self, app_label, state) -> None: ...
    def database_forwards(self, app_label, schema_editor, from_state, to_state) -> None: ...
    def database_backwards(self, app_label, schema_editor, from_state, to_state) -> None: ...
    def describe(self) -> str: ...
