from _typeshed import Incomplete

from django.db.migrations.operations.base import Operation

class PostgresPartitionOperation(Operation):
    model_name: Incomplete
    model_name_lower: Incomplete
    name: Incomplete
    def __init__(self, model_name: str, name: str) -> None: ...
    def deconstruct(self): ...
    def state_forwards(self, *args, **kwargs) -> None: ...
    def state_backwards(self, *args, **kwargs) -> None: ...
    def reduce(self, *args, **kwargs): ...
