from typing import Literal

from pandapower._typing import Float
from pandapower.auxiliary import pandapowerNet

def create_cigre_network_hv(length_km_6a_6b: Float = 0.1) -> pandapowerNet: ...
def create_cigre_network_mv(with_der: Literal["pv_wind", "all", False] = False) -> pandapowerNet: ...
def create_cigre_network_lv() -> pandapowerNet: ...
