from _typeshed import StrOrBytesPath, SupportsRead
from typing_extensions import Unpack

from pandapower._typing import Float, FromJsonKwds, Int
from pandapower.auxiliary import pandapowerNet

def sorted_from_json(path: SupportsRead[str] | StrOrBytesPath, **kwargs: Unpack[FromJsonKwds]) -> pandapowerNet: ...
def case4gs(**kwargs: Unpack[FromJsonKwds]) -> pandapowerNet: ...
def case5(**kwargs: Unpack[FromJsonKwds]) -> pandapowerNet: ...
def case6ww(**kwargs: Unpack[FromJsonKwds]) -> pandapowerNet: ...
def case9(**kwargs: Unpack[FromJsonKwds]) -> pandapowerNet: ...
def case11_iwamoto(**kwargs: Unpack[FromJsonKwds]) -> pandapowerNet: ...
def case14(**kwargs: Unpack[FromJsonKwds]) -> pandapowerNet: ...
def case24_ieee_rts(**kwargs: Unpack[FromJsonKwds]) -> pandapowerNet: ...
def case30(**kwargs: Unpack[FromJsonKwds]) -> pandapowerNet: ...
def case_ieee30(**kwargs: Unpack[FromJsonKwds]) -> pandapowerNet: ...
def case33bw(**kwargs: Unpack[FromJsonKwds]) -> pandapowerNet: ...
def case39(**kwargs: Unpack[FromJsonKwds]) -> pandapowerNet: ...
def case57(
    vn_kv_area1: Float = 115,
    vn_kv_area2: Float = 500,
    vn_kv_area3: Float = 138,
    vn_kv_area4: Float = 345,
    vn_kv_area5: Float = 230,
    vn_kv_area6: Float = 161,
    **kwargs: Unpack[FromJsonKwds],
) -> pandapowerNet: ...
def case89pegase(**kwargs: Unpack[FromJsonKwds]) -> pandapowerNet: ...
def case118(**kwargs: Unpack[FromJsonKwds]) -> pandapowerNet: ...
def case145(**kwargs: Unpack[FromJsonKwds]) -> pandapowerNet: ...
def case_illinois200(**kwargs: Unpack[FromJsonKwds]) -> pandapowerNet: ...
def case300(**kwargs: Unpack[FromJsonKwds]) -> pandapowerNet: ...
def case1354pegase(**kwargs: Unpack[FromJsonKwds]) -> pandapowerNet: ...
def case1888rte(ref_bus_idx: Int = 1246, **kwargs: Unpack[FromJsonKwds]) -> pandapowerNet: ...
def case2848rte(ref_bus_idx: Int = 271, **kwargs: Unpack[FromJsonKwds]) -> pandapowerNet: ...
def case2869pegase(**kwargs: Unpack[FromJsonKwds]) -> pandapowerNet: ...
def case3120sp(**kwargs: Unpack[FromJsonKwds]) -> pandapowerNet: ...
def case6470rte(ref_bus_idx: Int = 5988, **kwargs: Unpack[FromJsonKwds]) -> pandapowerNet: ...
def case6495rte(ref_bus_idx: Int | list[int] | None = None, **kwargs: Unpack[FromJsonKwds]) -> pandapowerNet: ...
def case6515rte(ref_bus_idx: Int = 6171, **kwargs: Unpack[FromJsonKwds]) -> pandapowerNet: ...
def case9241pegase(**kwargs: Unpack[FromJsonKwds]) -> pandapowerNet: ...
def GBreducednetwork(**kwargs: Unpack[FromJsonKwds]) -> pandapowerNet: ...
def GBnetwork(**kwargs: Unpack[FromJsonKwds]) -> pandapowerNet: ...
def iceland(**kwargs: Unpack[FromJsonKwds]) -> pandapowerNet: ...
