class HStoreRequiredSchemaEditorSideEffect:
    sql_hstore_required_create: str
    sql_hstore_required_rename: str
    sql_hstore_required_drop: str
    def create_model(self, model) -> None: ...
    def delete_model(self, model) -> None: ...
    def alter_db_table(self, model, old_db_table, new_db_table) -> None: ...
    def add_field(self, model, field) -> None: ...
    def remove_field(self, model, field) -> None: ...
    def alter_field(self, model, old_field, new_field, strict: bool = False) -> None: ...
