from _typeshed import Incomplete

MATPLOTLIB_INSTALLED: bool

def asarray(val, dtype=...): ...
def get_controller_index_by_type(net, ctrl_type, idx=...): ...
def get_controller_index_by_typename(net, typename, idx=..., case_sensitive: bool = ...): ...
def get_controller_index(net, ctrl_type: Incomplete | None = ..., parameters: Incomplete | None = ..., idx=...): ...
def log_same_type_existing_controllers(
    net, this_ctrl_type, index: Incomplete | None = ..., matching_params: Incomplete | None = ..., **kwargs
) -> None: ...
def drop_same_type_existing_controllers(
    net, this_ctrl_type, index: Incomplete | None = ..., matching_params: Incomplete | None = ..., **kwargs
) -> None: ...
def plot_characteristic(
    characteristic, start, stop, num: int = ..., xlabel: Incomplete | None = ..., ylabel: Incomplete | None = ...
) -> None: ...
def create_trafo_characteristics(net, trafotable, trafo_index, variable, x_points, y_points) -> None: ...
