from _typeshed import SupportsKeysAndGetItem
from collections.abc import Collection, Iterable

from pandapower._typing import Int
from pandapower.auxiliary import pandapowerNet

def getFromDict(dict_, keys): ...
def setInDict(dict_, keys, value) -> None: ...
def appendSetInDict(dict_, keys, set_) -> None: ...
def setSetInDict(dict_, keys, set_) -> None: ...
def append_set_to_dict(dict_, set_, keys) -> None: ...
def set_bus_zone_by_boundary_branches(
    net: pandapowerNet, all_boundary_branches: SupportsKeysAndGetItem[str, Collection[Int]]
) -> None: ...
def get_boundaries_by_bus_zone_with_boundary_branches(
    net: pandapowerNet,
) -> tuple[dict[str, dict[str, set[int]]], dict[str, dict[str, set[int]]]]: ...
def get_connected_switch_buses_groups(net: pandapowerNet, buses: Iterable[Int]) -> tuple[set[int], list[list[int]]]: ...
