name: Setup
description: Setup Python and install dependencies

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: pip
        cache-dependency-path: requirements.txt
    - name: Set up uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true
        cache-dependency-glob: "requirements.txt"
    - name: Install dependencies
      shell: bash
      run: uv pip install -r requirements.txt
