name: Setup
description: Setup Python and install dependencies

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - name: Set up uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true
        cache-dependency-glob: "requirements.txt"
    - name: Install Python 3.12
      shell: bash
      run: uv python install 3.12
    - name: Install dependencies
      shell: bash
      run: uv pip install -r requirements.txt
