from collections.abc import Collection, Iterable

from matplotlib.colors import BoundaryNorm, LinearSegmentedColormap, ListedColormap, LogNorm, Normalize

def cmap_discrete(cmap_list: Iterable[tuple[tuple[float, float], str]]) -> tuple[ListedColormap, BoundaryNorm]: ...
def cmap_continuous(cmap_list: Iterable[tuple[float, str]]) -> tuple[LinearSegmentedColormap, Normalize]: ...
def cmap_logarithmic(min_value: float, max_value: float, colors: Collection[str]) -> tuple[LinearSegmentedColormap, LogNorm]: ...
