from _typeshed import Incomplete

MATPLOTLIB_INSTALLED: bool

def node_patches(node_coords, size, patch_type, colors: Incomplete | None = ..., **kwargs): ...
def ellipse_patches(node_coords, width, height, angle: int = ..., color: Incomplete | None = ..., **kwargs): ...
def rectangle_patches(node_coords, width, height, color: Incomplete | None = ..., **kwargs): ...
def polygon_patches(node_coords, radius, num_edges, color: Incomplete | None = ..., **kwargs): ...
def load_patches(node_coords, size, angles, **kwargs): ...
def gen_patches(node_coords, size, angles, **kwargs): ...
def sgen_patches(node_coords, size, angles, **kwargs): ...
def storage_patches(node_coords, size, angles, **kwargs): ...
def ext_grid_patches(node_coords, size, angles, **kwargs): ...
def trafo_patches(coords, size, **kwargs): ...
