from _typeshed import Incomplete

def get_collection_sizes(
    net,
    bus_size: float = ...,
    ext_grid_size: float = ...,
    trafo_size: float = ...,
    load_size: float = ...,
    sgen_size: float = ...,
    switch_size: float = ...,
    switch_distance: float = ...,
    gen_size: float = ...,
): ...
def get_list(individuals, number_entries, name_ind, name_ent): ...
def get_color_list(color, number_entries, name_entries: str = ...): ...
def get_angle_list(angle, number_entries, name_entries: str = ...): ...
def get_linewidth_list(linewidth, number_entries, name_entries: str = ...): ...
def get_index_array(indices, net_table_indices): ...
def coords_from_node_geodata(
    element_indices, from_nodes, to_nodes, node_geodata, table_name, node_name: str = ..., ignore_zero_length: bool = ...
): ...
def set_line_geodata_from_bus_geodata(net, line_index: Incomplete | None = ..., overwrite: bool = ...) -> None: ...
def position_on_busbar(net, bus, busbar_coords): ...
