from _typeshed import Incomplete

def to_html(
    net, filename, respect_switches: bool = ..., include_lines: bool = ..., include_trafos: bool = ..., show_tables: bool = ...
) -> None: ...

class Raw:
    html: Incomplete
    def __init__(self, html) -> None: ...

class Tag:
    name: Incomplete
    def __init__(self, name) -> None: ...
    def __call__(self, *args, **kwargs): ...
