from _typeshed import Incomplete

from .partition import PostgresPartitionOperation

class PostgresAddHashPartition(PostgresPartitionOperation):
    modulus: Incomplete
    remainder: Incomplete
    def __init__(self, model_name: str, name: str, modulus: int, remainder: int) -> None: ...
    def state_forwards(self, app_label, state) -> None: ...
    def database_forwards(self, app_label, schema_editor, from_state, to_state) -> None: ...
    def database_backwards(self, app_label, schema_editor, from_state, to_state) -> None: ...
    def deconstruct(self): ...
    def describe(self) -> str: ...
