from django.db.migrations.operations.models import DeleteModel

class PostgresDeleteMaterializedViewModel(DeleteModel):
    def database_forwards(self, app_label, schema_editor, from_state, to_state) -> None: ...
    def database_backwards(self, app_label, schema_editor, from_state, to_state) -> None: ...
    def describe(self): ...
