from collections.abc import Generator
from contextlib import contextmanager

@contextmanager
def postgres_set_local(*, using: str = "default", **options: str | float | list[str] | None) -> Generator[None, None, None]: ...
@contextmanager
def postgres_set_local_search_path(search_path: list[str], *, using: str = "default") -> Generator[None, None, None]: ...
@contextmanager
def postgres_prepend_local_search_path(search_path: list[str], *, using: str = "default") -> Generator[None, None, None]: ...
@contextmanager
def postgres_reset_local_search_path(*, using: str = "default") -> Generator[None, None, None]: ...
