from _typeshed import Incomplete

from graph_tool import Graph

class GraphToolInterface(Graph):
    pp_buses: Incomplete
    def __init__(
        self, bus_indices, g: Incomplete | None = ..., directed: bool = ..., prune: bool = ..., vorder: Incomplete | None = ...
    ) -> None: ...
    def add_nodes_from(self, nodes) -> None: ...
    def add_node(self, node) -> None: ...
    def remove_node(self, node, fast: bool = ...) -> None: ...
    def remove_nodes(self, nodes): ...
    def nodes(self): ...
    def add_edge_data(self, edge) -> None: ...
    def get_edge_data(self, source, target, key: Incomplete | None = ...): ...
    def add_edge(self, source, target, add_missing: bool = ..., **kwargs) -> None: ...
    def is_multigraph(self): ...
