from _typeshed import Incomplete

import pandapower.auxiliary

class CreateMeasurements:
    net: Incomplete
    cim: Incomplete
    def __init__(self, net: pandapower.auxiliary.pandapowerNet, cim: dict) -> None: ...
    def update_assets_from_sv(self) -> None: ...
    def create_measurements_from_analog(self) -> None: ...
    def create_measurements_from_sv(self) -> None: ...
