import pandas as pd
from pandapower.auxiliary import pandapowerNet

def get_pp_net_special_columns_dict() -> dict[str, str]: ...
def extend_pp_net_cim(net: pandapowerNet, override: bool = ...) -> pandapowerNet: ...
def get_cim_data_structure() -> dict[str, dict[str, pd.DataFrame]]: ...
