import pandas as pd
from pandapower.auxiliary import pandapowerNet

def set_pp_col_types(net: pandapowerNet | dict, ignore_errors: bool = ...) -> pandapowerNet: ...
def add_slack_and_lines_to_boundary_nodes(net: pandapowerNet, voltage_levels: list[int] = ...): ...
def get_not_existing_column(df: pd.DataFrame) -> str: ...
