from _typeshed import Incomplete

def cancel(input_panel) -> None: ...
def calc_test(app, **kwargs) -> None: ...
def browse_dst_test(input_panel, entry_path_dst) -> None: ...
def conf_var_graphics(app, opt_grf, var_graphics) -> None: ...
def make_gui(app, project_name, browse_dst, calc): ...
