from _typeshed import Incomplete

def prj_import(com_import, dst_user_dir, file_name) -> None: ...
def prj_dgs_import(com_import, dst_user_dir, file_name, name, template: Incomplete | None = ...) -> None: ...
def choose_imp_dir(user, IMPFOLD): ...
def clear_dir(dir) -> None: ...
def run_ldf(com_ldf) -> None: ...
