def create_passive_external_net_for_ward_addmittance(
    net, all_external_buses, boundary_buses, calc_volt_angles: bool = ..., runpp_fct=...
) -> None: ...
def get_ppc_buses(net, buses, nogo_buses): ...
