from _typeshed import Incomplete

def desaturate(color, prop): ...
def saturate(color): ...
def set_hls_values(color, h: Incomplete | None = ..., l: Incomplete | None = ..., s: Incomplete | None = ...): ...
def despine(
    fig: Incomplete | None = ...,
    ax: Incomplete | None = ...,
    top: bool = ...,
    right: bool = ...,
    left: bool = ...,
    bottom: bool = ...,
    offset: Incomplete | None = ...,
    trim: bool = ...,
) -> None: ...
def move_legend(obj, loc, **kwargs) -> None: ...
def get_dataset_names(): ...
def get_data_home(data_home: Incomplete | None = ...): ...
def load_dataset(name, cache: bool = ..., data_home: Incomplete | None = ..., **kws): ...
