from _typeshed import Incomplete
from typing import Literal, overload

from matplotlib.colors import LinearSegmentedColormap

@overload
def choose_colorbrewer_palette(
    data_type: Literal["sequential", "diverging", "qualitative"], as_cmap: Literal[True]
) -> LinearSegmentedColormap: ...
@overload
def choose_colorbrewer_palette(
    data_type: Literal["sequential", "diverging", "qualitative"], as_cmap: Literal[False] = False
) -> list[Incomplete]: ...
@overload
def choose_colorbrewer_palette(
    data_type: Literal["sequential", "diverging", "qualitative"], as_cmap: bool = False
) -> LinearSegmentedColormap | list[Incomplete]: ...
@overload
def choose_dark_palette(input: str = "husl", *, as_cmap: Literal[True]) -> LinearSegmentedColormap: ...
@overload
def choose_dark_palette(input: str = "husl", as_cmap: Literal[False] = False) -> list[Incomplete]: ...
@overload
def choose_dark_palette(input: str = "husl", as_cmap: bool = False) -> LinearSegmentedColormap | list[Incomplete]: ...
@overload
def choose_light_palette(input: str = "husl", *, as_cmap: Literal[True]) -> LinearSegmentedColormap: ...
@overload
def choose_light_palette(input: str = "husl", as_cmap: Literal[False] = False) -> list[Incomplete]: ...
@overload
def choose_light_palette(input: str = "husl", as_cmap: bool = False) -> LinearSegmentedColormap | list[Incomplete]: ...
@overload
def choose_diverging_palette(as_cmap: Literal[True]) -> LinearSegmentedColormap: ...
@overload
def choose_diverging_palette(as_cmap: Literal[False] = False) -> list[Incomplete]: ...
@overload
def choose_diverging_palette(as_cmap: bool = False) -> LinearSegmentedColormap | list[Incomplete]: ...
@overload
def choose_cubehelix_palette(as_cmap: Literal[True]) -> LinearSegmentedColormap: ...
@overload
def choose_cubehelix_palette(as_cmap: Literal[False] = False) -> list[Incomplete]: ...
@overload
def choose_cubehelix_palette(as_cmap: bool = False) -> LinearSegmentedColormap | list[Incomplete]: ...
