from collections.abc import Collection

import numpy as np

from pandapower._typing import Array1D, Bool, Float, Int, ScalarOrVector
from pandapower.auxiliary import pandapowerNet

def create_impedance(
    net: pandapowerNet,
    from_bus: Int,
    to_bus: Int,
    rft_pu: Float,
    xft_pu: Float,
    sn_mva: Float,
    rtf_pu: Float | None = None,
    xtf_pu: Float | None = None,
    name: str | None = None,
    in_service: Bool = True,
    index: Int | None = None,
    rft0_pu: Float | None = None,
    xft0_pu: Float | None = None,
    rtf0_pu: Float | None = None,
    xtf0_pu: Float | None = None,
    gf_pu: Float = 0,
    bf_pu: Float = 0,
    gt_pu: Float | None = None,
    bt_pu: Float | None = None,
    gf0_pu: Float | None = None,
    bf0_pu: Float | None = None,
    gt0_pu: Float | None = None,
    bt0_pu: Float | None = None,
    **kwargs,
) -> np.int64: ...
def create_impedances(
    net: pandapowerNet,
    from_buses: Collection[Int],
    to_buses: Collection[Int],
    rft_pu: ScalarOrVector[Float],
    xft_pu: ScalarOrVector[Float],
    sn_mva: ScalarOrVector[Float],
    rtf_pu: ScalarOrVector[Float] | None = None,
    xtf_pu: ScalarOrVector[Float] | None = None,
    name: ScalarOrVector[str] | None = None,
    in_service: ScalarOrVector[Bool] = True,
    index: Collection[Int] | None = None,
    rft0_pu: ScalarOrVector[Float] | None = None,
    xft0_pu: ScalarOrVector[Float] | None = None,
    rtf0_pu: ScalarOrVector[Float] | None = None,
    xtf0_pu: ScalarOrVector[Float] | None = None,
    gf_pu: ScalarOrVector[Float] = 0,
    bf_pu: ScalarOrVector[Float] = 0,
    gt_pu: ScalarOrVector[Float] | None = None,
    bt_pu: ScalarOrVector[Float] | None = None,
    gf0_pu: ScalarOrVector[Float] | None = None,
    bf0_pu: ScalarOrVector[Float] | None = None,
    gt0_pu: ScalarOrVector[Float] | None = None,
    bt0_pu: ScalarOrVector[Float] | None = None,
    **kwargs,
) -> Array1D[np.int64]: ...
def create_tcsc(
    net: pandapowerNet,
    from_bus: Int,
    to_bus: Int,
    x_l_ohm: Float,
    x_cvar_ohm: Float,
    set_p_to_mw: Float,
    thyristor_firing_angle_degree: Float,
    name: str | None = None,
    controllable: Bool = True,
    in_service: Bool = True,
    index: Int | None = None,
    min_angle_degree: Float = 90,
    max_angle_degree: Float = 180,
    **kwargs,
) -> np.int64: ...
def create_series_reactor_as_impedance(
    net: pandapowerNet,
    from_bus: Int,
    to_bus: Int,
    r_ohm: Float,
    x_ohm: Float,
    sn_mva: Float,
    name: str | None = None,
    in_service: Bool = True,
    index: Int | None = None,
    r0_ohm: Float | None = None,
    x0_ohm: Float | None = None,
    **kwargs,
) -> np.int64: ...
