from collections.abc import Collection

import numpy as np

from pandapower._typing import Array1D, Bool, Float, Int, ScalarOrVector
from pandapower.auxiliary import pandapowerNet
from pandapower.pp_types import LineType

def create_line(
    net: pandapowerNet,
    from_bus: Int,
    to_bus: Int,
    length_km: Float,
    std_type: str,
    name: str | None = None,
    index: Int | None = None,
    geodata: Collection[tuple[Float, Float]] | None = None,
    df: Float = 1.0,
    parallel: Int = 1,
    in_service: Bool = True,
    max_loading_percent: Float = ...,
    alpha: Float = ...,
    temperature_degree_celsius: Float = ...,
    **kwargs,
) -> np.int64: ...
def create_line_dc(
    net: pandapowerNet,
    from_bus_dc: Int,
    to_bus_dc: Int,
    length_km: Float,
    std_type: str,
    name: str | None = None,
    index: Int | None = None,
    geodata: Collection[tuple[Float, Float]] | None = None,
    df: Float = 1.0,
    parallel: Int = 1,
    in_service: Bool = True,
    max_loading_percent: Float = ...,
    alpha: Float = ...,
    temperature_degree_celsius: Float = ...,
    **kwargs,
) -> np.int64: ...
def create_lines(
    net: pandapowerNet,
    from_buses: Collection[Int],
    to_buses: Collection[Int],
    length_km: ScalarOrVector[Float],
    std_type: ScalarOrVector[str],
    name: ScalarOrVector[str] | None = None,
    index: Collection[Int] | None = None,
    geodata: ScalarOrVector[Collection[tuple[Float, Float]]] | None = None,
    df: ScalarOrVector[Float] = 1.0,
    parallel: ScalarOrVector[Int] = 1,
    in_service: ScalarOrVector[Bool] = True,
    max_loading_percent: ScalarOrVector[Float] = ...,
    **kwargs,
) -> Array1D[np.int64]: ...
def create_lines_dc(
    net: pandapowerNet,
    from_buses_dc: Collection[Int],
    to_buses_dc: Collection[Int],
    length_km: ScalarOrVector[Float],
    std_type: ScalarOrVector[str],
    name: ScalarOrVector[str] | None = None,
    index: Collection[Int] | None = None,
    geodata: ScalarOrVector[Collection[tuple[Float, Float]]] | None = None,
    df: ScalarOrVector[Float] = 1.0,
    parallel: ScalarOrVector[Int] = 1,
    in_service: ScalarOrVector[Bool] = True,
    max_loading_percent: ScalarOrVector[Float] = ...,
    **kwargs,
) -> Array1D[np.int64]: ...
def create_line_from_parameters(
    net: pandapowerNet,
    from_bus: Int,
    to_bus: Int,
    length_km: Float,
    r_ohm_per_km: Float,
    x_ohm_per_km: Float,
    c_nf_per_km: Float,
    max_i_ka: Float,
    name: str | None = None,
    index: Int | None = None,
    type: LineType | None = None,
    geodata: Collection[tuple[Float, Float]] | None = None,
    in_service: Bool = True,
    df: Float = 1.0,
    parallel: Int = 1,
    g_us_per_km: Float = 0.0,
    max_loading_percent: Float = ...,
    alpha: Float = ...,
    temperature_degree_celsius: Float = ...,
    r0_ohm_per_km: Float = ...,
    x0_ohm_per_km: Float = ...,
    c0_nf_per_km: Float = ...,
    g0_us_per_km: Float = 0,
    endtemp_degree: Float = ...,
    **kwargs,
) -> np.int64: ...
def create_line_dc_from_parameters(
    net: pandapowerNet,
    from_bus_dc: Int,
    to_bus_dc: Int,
    length_km: Float,
    r_ohm_per_km: Float,
    max_i_ka: Float,
    name: str | None = None,
    index: Int | None = None,
    type: LineType | None = None,
    geodata: Collection[tuple[Float, Float]] | None = None,
    in_service: Bool = True,
    df: Float = 1.0,
    parallel: Int = 1,
    max_loading_percent: Float = ...,
    alpha: Float = ...,
    temperature_degree_celsius: Float = ...,
    g_us_per_km: Float = 0.0,
    **kwargs,
) -> np.int64: ...
def create_lines_from_parameters(
    net: pandapowerNet,
    from_buses: Collection[Int],
    to_buses: Collection[Int],
    length_km: ScalarOrVector[Float],
    r_ohm_per_km: ScalarOrVector[Float],
    x_ohm_per_km: ScalarOrVector[Float],
    c_nf_per_km: ScalarOrVector[Float],
    max_i_ka: ScalarOrVector[Float],
    name: ScalarOrVector[str] | None = None,
    index: Collection[Int] | None = None,
    type: ScalarOrVector[LineType] | None = None,
    geodata: ScalarOrVector[Collection[tuple[Float, Float]]] | None = None,
    in_service: ScalarOrVector[Bool] = True,
    df: ScalarOrVector[Float] = 1.0,
    parallel: ScalarOrVector[Int] = 1,
    g_us_per_km: ScalarOrVector[Float] = 0.0,
    max_loading_percent: ScalarOrVector[Float] = ...,
    alpha: ScalarOrVector[Float] = ...,
    temperature_degree_celsius: ScalarOrVector[Float] = ...,
    r0_ohm_per_km: ScalarOrVector[Float] = ...,
    x0_ohm_per_km: ScalarOrVector[Float] = ...,
    c0_nf_per_km: ScalarOrVector[Float] = ...,
    g0_us_per_km: ScalarOrVector[Float] = ...,
    **kwargs,
) -> Array1D[np.int64]: ...
def create_lines_dc_from_parameters(
    net: pandapowerNet,
    from_buses_dc: Collection[Int],
    to_buses_dc: Collection[Int],
    length_km: ScalarOrVector[Float],
    r_ohm_per_km: ScalarOrVector[Float],
    max_i_ka: ScalarOrVector[Float],
    name: ScalarOrVector[str] | None = None,
    index: Collection[Int] | None = None,
    type: ScalarOrVector[LineType] | None = None,
    geodata: ScalarOrVector[Collection[tuple[Float, Float]]] | None = None,
    in_service: ScalarOrVector[Bool] = True,
    df: ScalarOrVector[Float] = 1.0,
    parallel: ScalarOrVector[Int] = 1,
    g_us_per_km: ScalarOrVector[Float] = 0.0,
    max_loading_percent: ScalarOrVector[Float] = ...,
    alpha: ScalarOrVector[Float] = ...,
    temperature_degree_celsius: ScalarOrVector[Float] = ...,
    **kwargs,
) -> Array1D[np.int64]: ...
def create_dcline(
    net: pandapowerNet,
    from_bus: Int,
    to_bus: Int,
    p_mw: Float,
    loss_percent: Float,
    loss_mw: Float,
    vm_from_pu: Float,
    vm_to_pu: Float,
    index: Int | None = None,
    name: str | None = None,
    max_p_mw: Float = ...,
    min_q_from_mvar: Float = ...,
    min_q_to_mvar: Float = ...,
    max_q_from_mvar: Float = ...,
    max_q_to_mvar: Float = ...,
    in_service: Bool = True,
    **kwargs,
) -> np.int64: ...
