from collections.abc import Collection
from typing import Literal

import numpy as np

from pandapower._typing import Array1D, Bool, Float, Int, ScalarOrVector
from pandapower.auxiliary import pandapowerNet

def create_shunt(
    net: pandapowerNet,
    bus: Int,
    q_mvar: Float,
    p_mw: Float = 0.0,
    vn_kv: Float | None = None,
    step: Int = 1,
    max_step: Int = 1,
    name: str | None = None,
    step_dependency_table: Bool = False,
    id_characteristic_table: Int | None = None,
    in_service: Bool = True,
    index: Int | None = None,
    **kwargs,
) -> np.int64: ...
def create_shunts(
    net: pandapowerNet,
    buses: Collection[Int],
    q_mvar: ScalarOrVector[Float],
    p_mw: ScalarOrVector[Float] = 0.0,
    vn_kv: ScalarOrVector[Float] | None = None,
    step: ScalarOrVector[Int] = 1,
    max_step: ScalarOrVector[Int] = 1,
    name: ScalarOrVector[str] | None = None,
    step_dependency_table: ScalarOrVector[Bool] = False,
    id_characteristic_table: ScalarOrVector[Int] | None = None,
    in_service: ScalarOrVector[Bool] = True,
    index: Collection[Int] | None = None,
    **kwargs,
) -> Array1D[np.int64]: ...
def create_shunt_as_capacitor(
    net: pandapowerNet,
    bus: Int,
    q_mvar: Float,
    loss_factor: Float,
    *,
    # keywords passed to create_shunt extracted from **kwargs
    vn_kv: Float | None = None,
    step: Int = 1,
    max_step: Int = 1,
    name: str | None = None,
    step_dependency_table: Bool = False,
    id_characteristic_table: Int | None = None,
    in_service: Bool = True,
    index: Int | None = None,
    **kwargs,
) -> np.int64: ...
def create_svc(
    net: pandapowerNet,
    bus: Int,
    x_l_ohm: Float,
    x_cvar_ohm: Float,
    set_vm_pu: Float,
    thyristor_firing_angle_degree: Float,
    name: str | None = None,
    controllable: Bool = True,
    in_service: Bool = True,
    index: Int | None = None,
    min_angle_degree: Float = 90,
    max_angle_degree: Float = 180,
    **kwargs,
) -> np.int64: ...
def create_ssc(
    net: pandapowerNet,
    bus: Int,
    r_ohm: Float,
    x_ohm: Float,
    set_vm_pu: Float = 1.0,
    vm_internal_pu: Float = 1.0,
    va_internal_degree: Float = 0.0,
    name: str | None = None,
    controllable: Bool = True,
    in_service: Bool = True,
    index: Int | None = None,
    **kwargs,
) -> np.int64: ...
def create_b2b_vsc(
    net: pandapowerNet,
    bus: Int,
    bus_dc_plus: Int,
    bus_dc_minus: Int,
    r_ohm: Float,
    x_ohm: Float,
    r_dc_ohm: Float,
    pl_dc_mw: Float = 0.0,
    control_mode_ac: Literal["vm_pu", "q_mvar", "slack"] = "vm_pu",
    control_value_ac: Float = 1.0,
    control_mode_dc: Literal["vm_pu", "p_mw"] = "p_mw",
    control_value_dc: Float = 0.0,
    name: str | None = None,
    controllable: Bool = True,
    in_service: Bool = True,
    index: Int | None = None,
    **kwargs,
) -> np.int64: ...
def create_bi_vsc(
    net: pandapowerNet,
    bus: Int,
    bus_dc_plus: Int,
    bus_dc_minus: Int,
    r_ohm: Float,
    x_ohm: Float,
    r_dc_ohm: Float,
    pl_dc_mw: Float = 0.0,
    control_mode_ac: Literal["vm_pu", "q_mvar", "slack"] = "vm_pu",
    control_value_ac: Float = 1.0,
    control_mode_dc: Literal["vm_pu", "p_mw"] = "p_mw",
    control_value_dc: Float = 0.0,
    name: str | None = None,
    controllable: Bool = True,
    in_service: Bool = True,
    index: Int | None = None,
    **kwargs,
) -> np.int64: ...
def create_vsc(
    net: pandapowerNet,
    bus: Int,
    bus_dc: Int,
    r_ohm: Float,
    x_ohm: Float,
    r_dc_ohm: Float,
    pl_dc_mw: Float = 0.0,
    control_mode_ac: Literal["vm_pu", "q_mvar"] = "vm_pu",
    control_value_ac: Float = 1.0,
    control_mode_dc: Literal["vm_pu", "p_mw"] = "p_mw",
    control_value_dc: Float = 0.0,
    name: str | None = None,
    controllable: Bool = True,
    in_service: Bool = True,
    index: Int | None = None,
    ref_bus: Int | None = None,
    **kwargs,
) -> np.int64: ...
