import pandas as pd

from pandapower.auxiliary import pandapowerNet

def add_storage_opf_settings(net: pandapowerNet, ppci, pm) -> None: ...
def read_pm_storage_results(net: pandapowerNet) -> dict[int, pd.DataFrame]: ...
