from _typeshed import Incomplete

from pandapower.auxiliary import pandapowerNet

class CreateMeasurements:
    net: pandapowerNet
    cim: dict[Incomplete, Incomplete]
    def __init__(self, net: pandapowerNet, cim: dict[Incomplete, Incomplete]) -> None: ...
    def update_assets_from_sv(self) -> None: ...
    def create_measurements_from_analog(self) -> None: ...
    def create_measurements_from_sv(self) -> None: ...
