import numpy as np

from pandapower._typing import Array1D

def bustypes(bus, gen, vsc=None) -> tuple[Array1D[np.intp], Array1D[np.intp], Array1D[np.intp]]: ...
def bustypes_dc(bus_dc) -> tuple[Array1D[np.intp], Array1D[np.intp], Array1D[np.intp]]: ...
