import numpy as np
from numpy.typing import NDArray

def makeBdc(
    bus: NDArray[np.float64],
    branch: NDArray[np.float64],
    bus_dc: NDArray[np.float64] | None = None,
    branch_dc: NDArray[np.float64] | None = None,
    vsc: NDArray[np.float64] | None = None,
    return_csr: bool = True,
): ...
def phase_shift_injection(b, shift, Cft): ...
def calc_b_from_branch(branch, nl): ...
def calc_b_from_branch_dc(branch): ...
def calc_b_from_vsc_dc(vsc): ...
