import numpy as np

from pandapower._typing import Array2D

def update_LODF_diag(LODF) -> None: ...
def makeLODF(branch, PTDF): ...
def makeOTDF(PTDF, LODF, outage_branches): ...
def outage_results_OTDF(OTDF, Pbus, outage_branches) -> Array2D[np.float64]: ...
