from _typeshed import Incomplete

MATPLOTLIB_INSTALLED: bool

def get_plotly_color(color_string): ...
def get_plotly_color_palette(n): ...
def get_plotly_cmap(values, cmap_name: str = ..., cmin: Incomplete | None = ..., cmax: Incomplete | None = ...): ...
