from _typeshed import Incomplete
from typing import Any, NoReturn

from django.db.backends.base.base import BaseDatabaseWrapper
from django.db.models import IntegerField, Lookup, Transform, lookups
from django.db.models.expressions import BaseExpression
from django.db.models.sql.compiler import SQLCompiler

class InvalidLookup(Lookup[Incomplete]):
    def as_sql(self, qn: SQLCompiler, connection: BaseDatabaseWrapper) -> NoReturn: ...

class InvalidSearchLookup(Lookup[Incomplete]):
    def as_sql(self, qn: SQLCompiler, connection: BaseDatabaseWrapper) -> NoReturn: ...

class NetFieldDecoratorMixin:
    def process_lhs(
        self, qn: SQLCompiler, connection: BaseDatabaseWrapper, lhs: BaseExpression | None = None
    ) -> tuple[str, list[Any]]: ...

class EndsWith(NetFieldDecoratorMixin, lookups.EndsWith): ...
class IEndsWith(NetFieldDecoratorMixin, lookups.IEndsWith): ...
class StartsWith(NetFieldDecoratorMixin, lookups.StartsWith): ...
class IStartsWith(NetFieldDecoratorMixin, lookups.IStartsWith): ...
class Regex(NetFieldDecoratorMixin, lookups.Regex): ...
class IRegex(NetFieldDecoratorMixin, lookups.IRegex): ...

class NetworkLookup:
    def get_prep_lookup(self) -> str | BaseExpression: ...

class AddressLookup:
    def get_prep_lookup(self) -> str | BaseExpression: ...

class NetContains(AddressLookup, Lookup[Incomplete]):
    def as_sql(self, qn: SQLCompiler, connection: BaseDatabaseWrapper) -> tuple[str, list[Any]]: ...

class NetContained(NetworkLookup, Lookup[Incomplete]):
    def as_sql(self, qn: SQLCompiler, connection: BaseDatabaseWrapper) -> tuple[str, list[Any]]: ...

class NetContainsOrEquals(AddressLookup, Lookup[Incomplete]):
    def as_sql(self, qn: SQLCompiler, connection: BaseDatabaseWrapper) -> tuple[str, list[Any]]: ...

class NetContainedOrEqual(NetworkLookup, Lookup[Incomplete]):
    def as_sql(self, qn: SQLCompiler, connection: BaseDatabaseWrapper) -> tuple[str, list[Any]]: ...

class NetOverlaps(NetworkLookup, Lookup[Incomplete]):
    def as_sql(self, qn: SQLCompiler, connection: BaseDatabaseWrapper) -> tuple[str, list[Any]]: ...

class HostMatches(AddressLookup, Lookup[Incomplete]):
    def as_sql(self, qn: SQLCompiler, connection: BaseDatabaseWrapper) -> tuple[str, list[Any]]: ...

class Family(Transform):
    def as_sql(self, compiler: SQLCompiler, connection: BaseDatabaseWrapper) -> tuple[str, list[Any]]: ...  # type: ignore[override]
    @property
    def output_field(self) -> IntegerField[int]: ...

class _PrefixlenMixin:
    format_string: str | None
    def as_sql(self, qn: SQLCompiler, connection: BaseDatabaseWrapper) -> tuple[str, list[Any]]: ...
    def process_lhs(
        self, qn: SQLCompiler, connection: BaseDatabaseWrapper, lhs: BaseExpression | None = None
    ) -> tuple[str, list[Any]]: ...
    def get_prep_lookup(self) -> int: ...

class MaxPrefixlen(_PrefixlenMixin, Lookup[Incomplete]):
    format_string: str

class MinPrefixlen(_PrefixlenMixin, Lookup[Incomplete]):
    format_string: str

class Prefixlen(Transform):
    def as_sql(self, compiler: SQLCompiler, connection: BaseDatabaseWrapper) -> tuple[str, list[Any]]: ...  # type: ignore[override]
    @property
    def output_field(self) -> IntegerField[int]: ...
