from _typeshed import StrOrBytesPath, SupportsRead
from typing_extensions import Unpack

from pandapower.auxiliary import pandapowerNet
from pandapower.file_io import _FromJsonKwds

def sorted_from_json(path: SupportsRead[str] | StrOrBytesPath, **kwargs: Unpack[_FromJsonKwds]) -> pandapowerNet: ...
def case4gs(**kwargs: Unpack[_FromJsonKwds]) -> pandapowerNet: ...
def case5(**kwargs: Unpack[_FromJsonKwds]) -> pandapowerNet: ...
def case6ww(**kwargs: Unpack[_FromJsonKwds]) -> pandapowerNet: ...
def case9(**kwargs: Unpack[_FromJsonKwds]) -> pandapowerNet: ...
def case11_iwamoto(**kwargs: Unpack[_FromJsonKwds]) -> pandapowerNet: ...
def case14(**kwargs: Unpack[_FromJsonKwds]) -> pandapowerNet: ...
def case24_ieee_rts(**kwargs: Unpack[_FromJsonKwds]) -> pandapowerNet: ...
def case30(**kwargs: Unpack[_FromJsonKwds]) -> pandapowerNet: ...
def case_ieee30(**kwargs: Unpack[_FromJsonKwds]) -> pandapowerNet: ...
def case33bw(**kwargs: Unpack[_FromJsonKwds]) -> pandapowerNet: ...
def case39(**kwargs: Unpack[_FromJsonKwds]) -> pandapowerNet: ...
def case57(
    vn_kv_area1: float = 115,
    vn_kv_area2: float = 500,
    vn_kv_area3: float = 138,
    vn_kv_area4: float = 345,
    vn_kv_area5: float = 230,
    vn_kv_area6: float = 161,
    **kwargs: Unpack[_FromJsonKwds],
) -> pandapowerNet: ...
def case89pegase(**kwargs: Unpack[_FromJsonKwds]) -> pandapowerNet: ...
def case118(**kwargs: Unpack[_FromJsonKwds]) -> pandapowerNet: ...
def case145(**kwargs: Unpack[_FromJsonKwds]) -> pandapowerNet: ...
def case_illinois200(**kwargs: Unpack[_FromJsonKwds]) -> pandapowerNet: ...
def case300(**kwargs: Unpack[_FromJsonKwds]) -> pandapowerNet: ...
def case1354pegase(**kwargs: Unpack[_FromJsonKwds]) -> pandapowerNet: ...
def case1888rte(ref_bus_idx: int = 1246, **kwargs: Unpack[_FromJsonKwds]) -> pandapowerNet: ...
def case2848rte(ref_bus_idx: int = 271, **kwargs: Unpack[_FromJsonKwds]) -> pandapowerNet: ...
def case2869pegase(**kwargs: Unpack[_FromJsonKwds]) -> pandapowerNet: ...
def case3120sp(**kwargs: Unpack[_FromJsonKwds]) -> pandapowerNet: ...
def case6470rte(ref_bus_idx: int = 5988, **kwargs: Unpack[_FromJsonKwds]) -> pandapowerNet: ...
def case6495rte(ref_bus_idx: int | list[int] | None = None, **kwargs: Unpack[_FromJsonKwds]) -> pandapowerNet: ...
def case6515rte(ref_bus_idx: int = 6171, **kwargs: Unpack[_FromJsonKwds]) -> pandapowerNet: ...
def case9241pegase(**kwargs: Unpack[_FromJsonKwds]) -> pandapowerNet: ...
def GBreducednetwork(**kwargs: Unpack[_FromJsonKwds]) -> pandapowerNet: ...
def GBnetwork(**kwargs: Unpack[_FromJsonKwds]) -> pandapowerNet: ...
def iceland(**kwargs: Unpack[_FromJsonKwds]) -> pandapowerNet: ...
