from pandapower.auxiliary import pandapowerNet

def panda_four_load_branch() -> pandapowerNet: ...
def four_loads_with_branches_out() -> pandapowerNet: ...
def simple_four_bus_system() -> pandapowerNet: ...
def simple_mv_open_ring_net() -> pandapowerNet: ...
