from collections.abc import Iterable, Iterator, Mapping
from typing import Any

from django.db.models import Model

def models_from_cursor[M: Model](model: type[M], cursor, *, related_fields: Iterable[str] = []) -> Iterator[M]: ...
def model_from_cursor[M: Model](model: type[M], cursor, *, related_fields: Iterable[str] = []) -> M | None: ...
def model_from_dict[M: Model](model: type[M], row: Mapping[str, Any], *, apply_converters: bool = True) -> M: ...
