from django.db.models.sql import compiler as django_compiler

def append_caller_to_sql(sql: str) -> str: ...

class SQLCompiler(django_compiler.SQLCompiler): ...
class SQLDeleteCompiler(django_compiler.SQLDeleteCompiler): ...
class SQLAggregateCompiler(django_compiler.SQLAggregateCompiler): ...
class SQLUpdateCompiler(django_compiler.SQLUpdateCompiler): ...
class SQLInsertCompiler(django_compiler.SQLInsertCompiler): ...
class PostgresInsertOnConflictCompiler(django_compiler.SQLInsertCompiler): ...
