from pandapower.auxiliary import pandapowerNet

def three_radial_bus_net() -> pandapowerNet: ...
def dtoc_relay_net(open_loop: bool = True) -> pandapowerNet: ...
def idmt_relay_net(open_loop: bool = True) -> pandapowerNet: ...
def idtoc_relay_net(open_loop: bool = True) -> pandapowerNet: ...
