from typing import TypeVar

_YxT = TypeVar("_YxT")  # probably bound to ndarray

def dSbus_dV_numba_sparse(Yx: _YxT, Yp, Yj, V, Vnorm, Ibus) -> tuple[_YxT, _YxT]: ...
def dSbus_dV(Ybus, V, I=None): ...
