from _typeshed import Incomplete

from numpy import arange as arange, dot as dot

class opf_model:
    ppc: Incomplete
    var: Incomplete
    nln: Incomplete
    lin: Incomplete
    cost: Incomplete
    user_data: Incomplete
    def __init__(self, ppc) -> None: ...
    def add_constraints(self, name, AorN, l, u: Incomplete | None = ..., varsets: Incomplete | None = ...) -> None: ...
    def add_vars(
        self, name, N, v0: Incomplete | None = ..., vl: Incomplete | None = ..., vu: Incomplete | None = ...
    ) -> None: ...
    def build_cost_params(self) -> None: ...
    def get_cost_params(self): ...
    def get_idx(self): ...
    def get_ppc(self): ...
    def getN(self, selector, name: Incomplete | None = ...): ...
    def getv(self): ...
    def linear_constraints(self): ...
    def userdata(self, name, val: Incomplete | None = ...): ...
