from _typeshed import Incomplete

class opf_model:
    ppc: Incomplete
    var: Incomplete
    nln: Incomplete
    lin: Incomplete
    cost: Incomplete
    user_data: Incomplete
    def __init__(self, ppc) -> None: ...
    def add_constraints(self, name, AorN, l, u: Incomplete | None = None, varsets: Incomplete | None = None) -> None: ...
    def add_vars(
        self, name, N, v0: Incomplete | None = None, vl: Incomplete | None = None, vu: Incomplete | None = None
    ) -> None: ...
    def build_cost_params(self) -> None: ...
    def get_cost_params(self): ...
    def get_idx(self): ...
    def get_ppc(self): ...
    def getN(self, selector, name: Incomplete | None = None): ...
    def getv(self): ...
    def linear_constraints(self): ...
    def userdata(self, name, val: Incomplete | None = None): ...
