from _typeshed import Incomplete

def add_gen_order(gen_order, element, _is_elements, f) -> Incomplete: ...
def add_element_to_gen(net, ppc, element, f, t) -> None: ...
def add_q_constraints(net, element, is_element, ppc, f, t, delta, inverted: bool = ...) -> None: ...
def add_p_constraints(net, element, is_element, ppc, f, t, delta, inverted: bool = ...) -> None: ...
