from pandapower.auxiliary import pandapowerNet

def get_trafo_values(trafo_df, par): ...
def get_is_lines(net: pandapowerNet) -> None: ...
def z_br_to_bus_vector(z, sn): ...
def wye_delta(zbr_n, s): ...
def wye_delta_vector(zbr_n, s): ...
