from dataclasses import dataclass

from psqlextra.partitioning.config import PostgresPartitioningConfig
from psqlextra.partitioning.partition import PostgresPartition

__all__ = ["PostgresPartitioningPlan", "PostgresModelPartitioningPlan"]

@dataclass
class PostgresModelPartitioningPlan:
    config: PostgresPartitioningConfig
    creations: list[PostgresPartition] = ...
    deletions: list[PostgresPartition] = ...
    def apply(self, using: str | None) -> None: ...
    def print(self) -> None: ...

@dataclass
class PostgresPartitioningPlan:
    model_plans: list[PostgresModelPartitioningPlan]
    @property
    def creations(self) -> list[PostgresPartition]: ...
    @property
    def deletions(self) -> list[PostgresPartition]: ...
    def apply(self, using: str | None = None) -> None: ...
    def print(self) -> None: ...
