from psqlextra.partitioning.config import PostgresPartitioningConfig
from psqlextra.partitioning.partition import PostgresPartition

class PostgresModelPartitioningPlan:
    config: PostgresPartitioningConfig
    creations: list[PostgresPartition]
    deletions: list[PostgresPartition]
    def apply(self, using: str | None) -> None: ...
    def print(self) -> None: ...
    def __init__(self, config, creations, deletions) -> None: ...

class PostgresPartitioningPlan:
    model_plans: list[PostgresModelPartitioningPlan]
    @property
    def creations(self) -> list[PostgresPartition]: ...
    @property
    def deletions(self) -> list[PostgresPartition]: ...
    def apply(self, using: str | None = ...) -> None: ...
    def print(self) -> None: ...
    def __init__(self, model_plans) -> None: ...
