from typing import Any

from numpy.typing import DTypeLike, NDArray

from pandapower.auxiliary import pandapowerNet

def asarray(val: object, dtype: DTypeLike = ...) -> NDArray[Any]: ...
def get_controller_index_by_type(net: pandapowerNet, ctrl_type, idx=[]): ...
def get_controller_index_by_typename(net: pandapowerNet, typename, idx=[], case_sensitive: bool = False): ...
def get_controller_index(net: pandapowerNet, ctrl_type=None, parameters=None, idx=[]): ...
def log_same_type_existing_controllers(
    net: pandapowerNet, this_ctrl_type, index=None, matching_params=None, **kwargs
) -> None: ...
def drop_same_type_existing_controllers(
    net: pandapowerNet, this_ctrl_type, index=None, matching_params=None, **kwargs
) -> None: ...
def plot_characteristic(characteristic, start, stop, num: int = 20, xlabel=None, ylabel=None) -> None: ...
def create_trafo_characteristic_object(net: pandapowerNet) -> None: ...
def _create_trafo_characteristics(net: pandapowerNet, trafotable, trafo_index, variable, x_points, y_points) -> None: ...
def create_shunt_characteristic_object(net: pandapowerNet) -> None: ...
def create_q_capability_characteristics_object(net: pandapowerNet) -> None: ...
