from pandapower.auxiliary import pandapowerNet

def control_diagnostic(net: pandapowerNet, respect_in_service: bool = True) -> None: ...
def trafo_characteristic_table_diagnostic(net: pandapowerNet) -> bool: ...
def shunt_characteristic_table_diagnostic(net: pandapowerNet) -> bool: ...
def q_capability_curve_table_diagnostic(net: pandapowerNet, element: str) -> bool: ...
